# <p style="text-align: center;"> MÓDULO 4 - EXPLORATORY DATA ANALYTICS </p>
## Aula 2

### <span style="color: blue;"> * **Exercicio 1**</span>

**Passo 1** - Importar os dados do ficheiro **Carros2** para uma DataFrame chamada **Carros2**.

In [2]:
import pandas as pd

In [4]:
caminho = r'C:\Users\aninh\Desktop\study\Data Science and Business Analist\Exploratory Data\exercicio 3\Carros2.csv'

Carros2 = pd.read_csv(caminho)

**Passo 2** - Explorar **conteúdo** da tabela e identificar potenciais situações de erro.

In [5]:
Carros2.head()

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-size,horsepower,price
0,volkswagen,?,std,four,sedan,fwd,front,97.3,171.7,65.5,55.7,2300,109,100.0,9995
1,honda,gas,std,two,sedan,fwd,front,96.5,169.1,66.0,51.0,2293,110,100.0,10345
2,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,108,101.0,16430
3,mazda,gas,std,two,hatchback,rwd,front,95.3,169.0,65.7,49.6,2380,70,101.0,11845
4,honda,gas,std,four,sedan,fwd,front,96.5,175.4,65.2,54.1,2465,110,101.0,12945

In [6]:
print(Carros2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   make             201 non-null    object
 1   fuel-type        201 non-null    object
 2   aspiration       201 non-null    object
 3   num-of-doors     199 non-null    object
 4   body-style       201 non-null    object
 5   drive-wheels     201 non-null    object
 6   engine-location  201 non-null    object
 7   wheel-base       201 non-null    float64
 8   length           201 non-null    float64
 9   width            201 non-null    float64
 10  height           201 non-null    object
 11  curb-weight      201 non-null    int64
 12  engine-size      201 non-null    int64
 13  horsepower       199 non-null    float64
 14  price            201 non-null    object
dtypes: float64(4), int64(2), object(9)
memory usage: 23.7+ KB
None

In [7]:
Carros2.describe()

,wheel-base,length,width,curb-weight,engine-size,horsepower
count,201.000000,201.000000,201.000000,201.000000,201.000000,199.000000
mean,98.797015,174.200995,65.889055,2555.666667,126.875622,103.396985
std,6.066366,12.322175,2.101471,517.296727,41.546834,37.553843
min,86.600000,141.100000,60.300000,1488.000000,61.000000,48.000000
25%,94.500000,166.800000,64.100000,2169.000000,98.000000,70.000000
50%,97.000000,173.200000,65.500000,2414.000000,120.000000,95.000000
75%,102.400000,183.500000,66.600000,2926.000000,141.000000,116.000000
max,120.900000,208.100000,72.000000,4066.000000,326.000000,262.000000

**Passo 3** - *Identificar missing values* e converte-los para o **formato NaN**.

In [8]:
Carros2.isnull().sum()

make               0
fuel-type          0
aspiration         0
num-of-doors       2
body-style         0
drive-wheels       0
engine-location    0
wheel-base         0
length             0
width              0
height             0
curb-weight        0
engine-size        0
horsepower         2
price              0
dtype: int64

In [11]:
import numpy as np

In [19]:
Carros2.replace('?',np.nan, inplace = True)

**Passo 4** - Corrigir **tipologia** das colunas, caso necessário.

In [17]:
Carros2["height"] = Carros2["height"].astype("float")
Carros2["horsepower"] = Carros2["horsepower"].astype("float")
Carros2["price"] = Carros2["price"].astype("float")

print(Carros2.dtypes)

make                object
fuel-type           object
aspiration          object
num-of-doors        object
body-style          object
drive-wheels        object
engine-location     object
wheel-base         float64
length             float64
width              float64
height             float64
curb-weight          int64
engine-size          int64
horsepower         float64
price              float64
dtype: object

**Passo 5** - Indicar o **total** de observações com *missing values* e o **número de *missing values* por variável**.

In [18]:
print("Missing values por variável:")
print(Carros2.isnull().sum())

print("-" * 30)

total_linhas_com_na = Carros2.isnull().any(axis=1).sum()

print(f"Total de observações com missing values: {total_linhas_com_na}")

Missing values por variável:
make               0
fuel-type          4
aspiration         0
num-of-doors       2
body-style         0
drive-wheels       0
engine-location    0
wheel-base         0
length             0
width              0
height             1
curb-weight        0
engine-size        0
horsepower         2
price              1
dtype: int64
------------------------------
Total de observações com missing values: 8

**Passo 6** - No caso da variável **price**, caso ela tenha missing values, faz **drop** das observações.

In [20]:
Carros2.dropna(subset=["price"], axis=0, inplace=True)
Carros2.reset_index(drop=True, inplace=True)

**Passo 7** - Caso existam missing values noutras **variáveis quantitativas**, substitui-os pela **média**.

In [21]:
avg_hp = Carros2["horsepower"].astype("float").mean(axis=0)
Carros2["horsepower"] = Carros2["horsepower"].replace(np.nan, avg_hp)

avg_height = Carros2["height"].astype("float").mean(axis=0)
Carros2["height"] = Carros2["height"].replace(np.nan, avg_height)

**Passo 8** - Caso existam *missing values* noutras **variáveis qualitativas**, substitui-os pela **moda**.

In [22]:
most_common_fuel = Carros2['fuel-type'].value_counts().idxmax()
Carros2["fuel-type"] = Carros2["fuel-type"].replace(np.nan, most_common_fuel)

most_common_doors = Carros2['num-of-doors'].value_counts().idxmax()
Carros2["num-of-doors"] = Carros2["num-of-doors"].replace(np.nan, most_common_doors)

**Passo 9** - Confirma que não existem mais valores em falta no dataframe e que está **pronto para a fase seguinte**.

In [23]:
print(Carros2.isnull().sum())

make               0
fuel-type          0
aspiration         0
num-of-doors       0
body-style         0
drive-wheels       0
engine-location    0
wheel-base         0
length             0
width              0
height             0
curb-weight        0
engine-size        0
horsepower         0
price              0
dtype: int64

# <p style="text-align: center;"> MÓDULO 4 - EXPLORATORY DATA ANALYTICS </p>
## Aula 2

### <span style="color: blue;"> * **Exercicio 2**</span>

**Passo 10** - Avaliar os **principais indicadores** das variáveis quantitativas e verifica se existe um **problema de escalas**.

In [24]:
print(Carros2.describe())

       wheel-base     length       width      height  curb-weight  \
count  200.000000  200.00000  200.000000  200.000000   200.000000
mean    98.792000  174.18900   65.887500   53.780402  2556.760000
std      6.081171   12.35192    2.106628    2.442683   518.361966
min     86.600000  141.10000   60.300000   47.800000  1488.000000
25%     94.500000  166.67500   64.100000   52.000000  2163.000000
50%     96.950000  173.20000   65.500000   54.100000  2417.000000
75%    102.400000  183.50000   66.675000   55.525000  2928.250000
max    120.900000  208.10000   72.000000   59.800000  4066.000000

       engine-size  horsepower         price
count   200.000000  200.000000    200.000000
mean    126.965000  103.404040  13203.415000
std      41.631716   37.459236   7966.833912
min      61.000000   48.000000   5118.000000
25%      97.750000   70.000000   7775.000000
50%     120.000000   95.000000  10270.000000
75%     142.000000  116.000000  16500.750000
max     326.000000  262.000000  45400.000000

**Passo 11** - Criar uma nova variável **length_min_max** através da transformação **Min-Max** aplicada à variável **length**. Valida se os valores da nova variável são os **previstos pela transformação**.

In [25]:
Carros2['length_min_max'] = (Carros2['length'] - Carros2['length'].min()) / (Carros2['length'].max() - Carros2['length'].min())

print(Carros2[['length', 'length_min_max']].describe())

          length  length_min_max
count  200.00000      200.000000
mean   174.18900        0.493866
std     12.35192        0.184357
min    141.10000        0.000000
25%    166.67500        0.381716
50%    173.20000        0.479104
75%    183.50000        0.632836
max    208.10000        1.000000

**Passo 12** - Criar uma nova variável **width_std** através da **estandardização** da variável **width**. Validar se os novos valores da variável são os **previstos pela transformação**.

In [26]:
Carros2['width_std'] = (Carros2['width'] - Carros2['width'].mean()) / Carros2['width'].std()
print(Carros2[['width', 'width_std']].describe())

            width     width_std
count  200.000000  2.000000e+02
mean    65.887500 -9.237056e-16
std      2.106628  1.000000e+00
min     60.300000 -2.652342e+00
25%     64.100000 -8.485123e-01
50%     65.500000 -1.839432e-01
75%     66.675000  3.738201e-01
max     72.000000  2.901556e+00

**Passo 13** - Criar uma nova variável **height_log** através de uma transformação **Logarítmica** aplicada a **height**. Validar se os novos valores da variável são os **previstos pela transformação**.

In [27]:
Carros2['height_log'] = np.log(Carros2['height'])
print(Carros2[['height', 'height_log']].head())

   height  height_log
0    55.7    4.019980
1    51.0    3.931826
2    54.3    3.994524
3    49.6    3.903991
4    54.1    3.990834

**Passo 14** - Cria uma nova variável **price_decile** através da transformação **em decis** da variável **price**. Valida se os valores da nova variável são os **previstos pela transformação**.

In [28]:
Carros2['price_decile'] = pd.qcut(Carros2['price'], q=10, labels=False) + 1
print(Carros2['price_decile'].value_counts().sort_index())

price_decile
1     20
2     20
3     20
4     20
5     20
6     20
7     20
8     20
9     20
10    20
Name: count, dtype: int64

**Passo 15** - **Exportar** os dados de Carros2 num ficheiro csv com o nome **Carros3**

In [29]:
Carros2.to_csv('Carros3.csv', index=False)